apiVersion: kubeaction.spaceone.dev/v1alpha1
kind: Flow
metadata:
  name: action-all
spec:
  metadata:
    repository: https://github.com/wesky93/test_action
    github_token:
      secrets_provider: kubernetes
      name: spaceone-github
      key: token

  events:
    schedule:
      - cron:  '*/2 * * * *'
  jobs:
    first:
      runs-on: ubuntu-latest
      steps:
        - name: showTest
          id: request
          run: echo 'test'
        - name: showTest
          id: request2
          run: |
            echo 'test'
            echo 'test2'
        - uses: actions/checkout@v2
        - name: print
          run: ls -al
        - name: dockerAction
          uses: wesky93/debug-action@master
    second:
      runs-on: ubuntu-latest
      steps:
        - name: showTest
          id: request
          run: echo 'test'
        - uses: actions/checkout@v2
        - name: print
          run: ls -al
        - name: dockerAction
          uses: wesky93/debug-action@master
